FROM postgis/postgis:14-3.5
RUN localedef -i fi_FI -c -f UTF-8 -A /usr/share/locale/locale.alias fi_FI.UTF8
ENV LANG fi_FI.utf8
COPY init_db.sql /docker-entrypoint-initdb.d/
COPY dump.backup /docker-entrypoint-initdb.d/dump.backup
COPY restore_dump.sh /docker-entrypoint-initdb.d/zz_restore_dump.sh
RUN chmod +x /docker-entrypoint-initdb.d/zz_restore_dump.sh
